left to right direction

skinparam wrapWidth 150

skinparam node {
	BorderColor #666666
	BackgroundColor AZURE_BG_COLOR
  FontColor #666666
  FontSize 13
}

skinparam actor {
	BorderColor #666666
	BackgroundColor AZURE_BG_COLOR
  FontColor #666666
  FontSize 13
}

skinparam rectangle {
  BorderColor AZURE_BORDER_COLOR
	BackgroundColor AZURE_BG_COLOR
}