@startuml

!include _common.wsd
!include _azure-plantuml.wsd

node "**External Building System**" as externalBuildingSystemAlias

AzureEventHub(rawEventsHubAlias, "Raw Event Hub", "Events")
AzureFunction(stateFunctionAlias, "State Processor", "Compute")
AzureCosmosDb(stateDBAlias, "State Database", "Database")
AzureDataLakeStorage(datalakeAlias, "Data Lake", "Storage")
AzureStreamAnalytics(streamAnalyticsAlias, "Aggregate Events", "Analytics")
AzureEventHub(aggregatedEventsHubAlias, "Aggregated Hub", "Events")
AzureTimeSeriesInsights(timeSeriesAlias, "Time Series", "Database")

externalBuildingSystemAlias --> rawEventsHubAlias
rawEventsHubAlias --> datalakeAlias : **Capture** 
rawEventsHubAlias --> stateFunctionAlias
rawEventsHubAlias --> streamAnalyticsAlias
streamAnalyticsAlias --> aggregatedEventsHubAlias
aggregatedEventsHubAlias --> timeSeriesAlias
stateFunctionAlias --> stateDBAlias

actor "**API Users**" as apiUsersAlias
timeSeriesAlias <-. apiUsersAlias
datalakeAlias <-. apiUsersAlias
stateDBAlias <-. apiUsersAlias

@enduml